### PR TITLE
disable try again button after otp is sent

### PR DESCRIPTION
**Pull request by sahell0x**

### CODE REVIEW

**Comment by LordNayan** [comment]
Hi @sahell0x , can you please remove changes from the lock file.

**Comment by Abhishek9503** [comment]
Hi @sahell0x currently we are working on the same module for the revamp and we have changed some folder structure in this repo , so merging your PR will result in merge conflict , although we have fixed the disable button issue when we click on button

**Comment by sahell0x** [comment]
> Hi @sahell0x currently we are working on the same module for the revamp and we have changed some folder structure in this repo , so merging your PR will result in merge conflict , although we have fixed the disable button issue when we click on button

Completely understandable.

**Review by itsmdasifraza — APPROVED** [review]

**Comment by itsmdasifraza** [comment]
LGTM 🎇

**Pull request merged**
